# Generated by Django 3.2.7 on 2021-09-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_account_no', models.CharField(blank=True, max_length=120, null=True, verbose_name='Loan Account Number')),
                ('mobile_no', models.CharField(blank=True, max_length=120, null=True, verbose_name='Mobile Number')),
                ('template_id', models.IntegerField(blank=True, null=True, verbose_name='Template ID')),
                ('request', models.JSONField()),
                ('response', models.JSONField()),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RetrivedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Customer Name')),
                ('due_amount', models.IntegerField(blank=True, null=True, verbose_name='Due Amount')),
                ('template_id', models.IntegerField(blank=True, null=True, verbose_name='Template ID')),
                ('batch_id', models.IntegerField(blank=True, null=True, verbose_name='Batch ID')),
                ('mobile_no', models.CharField(blank=True, max_length=120, null=True, verbose_name='Mobile Number')),
                ('loan_account_no', models.CharField(blank=True, max_length=120, null=True, verbose_name='Loan Account Number')),
                ('status', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField()),
                ('scheduled_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('response', models.JSONField()),
            ],
        ),
    ]
