# Generated by Django 3.2.7 on 2021-09-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retriveddata',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
