# Generated by Django 3.2.7 on 2021-09-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineapp', '0002_alter_retriveddata_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retriveddata',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retriveddata',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retriveddata',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retriveddata',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
